spring:
  profiles:
    active: dev
  application:
    name: middleware-server
  datasource:
    url: jdbc:mysql://${jacolp.datasource.host}:${jacolp.datasource.port}/${jacolp.datasource.database}
    username: ${jacolp.datasource.username}
    password: ${jacolp.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      keep-alive-time: 50000  # 50 秒尝试一次保持 TCP 连接
      connection-test-query: SELECT 1

jacolp:
  admin:
    username: ${jacolp.admin.username}
    password: ${jacolp.admin.password}
  default-password: ${jacolp.default-password}
  jwt:
    admin-secret-key: ${jwt.admin-secret-key}
    admin-ttl: 7200000
    admin-token-name: ${jwt.admin-token-name}
    user-secret-key: ${jwt.user-secret-key}
    user-ttl: 7200000
    user-token-name: ${jwt.user-token-name}
  markdown:
    root: ${jacolp.markdown.root}
    input-dir: ${jacolp.markdown.input}
    output-dir: ${jacolp.markdown.output}
  aliyun:
    oss:
      keep-live-time: 45  # 单位是秒
      enabled: true
  image:
    delete-image-task-time: 1 # 单位是分钟

aliyun:
  oss:
    endpoint: https://${jacolp.aliyun.oss.endpoint}
    bucket-name: ${jacolp.aliyun.oss.bucket-name}
    region: ${jacolp.aliyun.oss.region}

# 开启驼峰命名转换
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true