package com.jacolp.middleware.common.security.oauth2.token;
import org.junit.jupiter.api.*; import org.springframework.data.redis.core.*; import org.springframework.security.crypto.bcrypt.BCrypt; import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
class RedisOAuth2TokenStateStoreTest {
 static final String FP="AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8", JTI="AAECAwQFBgcICQoLDA0ODw"; StringRedisTemplate redis; HashOperations hash; RedisOAuth2TokenStateStore store; OAuth2TokenStateCodec codec=new OAuth2TokenStateCodec(); RefreshTokenState refresh; OAuth2SessionState session;
 @BeforeEach void init(){redis=mock(StringRedisTemplate.class);hash=mock(HashOperations.class);when(redis.opsForHash()).thenReturn(hash); Instant n=Instant.parse("2026-08-10T00:00:00Z");refresh=new RefreshTokenState(FP, BCrypt.hashpw("x",BCrypt.gensalt()),1,"core_agent",List.of(),n,n.plusSeconds(1));session=new OAuth2SessionState(1,"core_agent",JTI,n,FP,n);store=new RedisOAuth2TokenStateStore(redis,codec);}
 @Test void findsStatesAtExactKeysAndDeletes(){when(hash.entries("user:refresh:"+FP)).thenReturn(codec.encode(refresh));when(hash.entries("user:session:core_agent:1")).thenReturn(codec.encode(session));assertThat(store.findRefreshByFingerprint(FP)).contains(refresh);assertThat(store.findSession("core_agent",1)).contains(session);store.deleteRefresh(FP);store.deleteSession("core_agent",1);verify(redis).delete("user:refresh:"+FP);verify(redis).delete("user:session:core_agent:1");}
 @Test void treatsEmptyHashAsMissingAndRejectsPollution(){when(hash.entries(anyString())).thenReturn(Map.of());assertThat(store.findRefreshByFingerprint(FP)).isEmpty();assertThat(store.findSession("core_agent",1)).isEmpty();when(hash.entries("user:refresh:"+FP)).thenReturn(Map.of("schema_version","1"));assertThatIllegalArgumentException().isThrownBy(()->store.findRefreshByFingerprint(FP));}
 @Test void rejectsKeyStateMismatch(){Map<String,String> polluted=new HashMap<>(codec.encode(refresh));polluted.put("fingerprint","BBECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8");when(hash.entries("user:refresh:"+FP)).thenReturn(polluted);assertThatIllegalArgumentException().isThrownBy(()->store.findRefreshByFingerprint(FP));}
}
