/**
 * Share-link values are opaque credentials.  Keep their accepted shape in one
 * place so the router and API client fail closed in exactly the same way.
 */
export const SHARE_LINK_CODE_PATTERN = /^[A-Za-z0-9_-]{43}$/

const SHARE_ROUTE_PATTERN = /^\/share\/documents\/([A-Za-z0-9_-]{43})$/

export type ShareLoginLocation = '/login' | {
  path: '/login'
  query: { redirect: string }
}

export interface ShareDocumentRouteLocation {
  name: 'UserDocumentEditor'
  params: { documentId: string }
}

/** Validate the 256-bit Base64URL code generated by the server. */
export function isValidShareLinkCode(value: unknown): value is string {
  return typeof value === 'string' && SHARE_LINK_CODE_PATTERN.test(value)
}

/**
 * Return a redirect only when it is the exact internal share route.
 *
 * The URL parser rejects absolute URLs, protocol-relative URLs, query strings
 * and fragments.  The fixed host is only a parsing sentinel; the returned
 * value is always a pathname on this SPA.
 */
export function sanitizeShareRedirect(value: unknown): string | null {
  if (typeof value !== 'string' || !value.startsWith('/') || value.startsWith('//')) return null

  try {
    const parsed = new URL(value, 'https://share-redirect.invalid')
    if (parsed.origin !== 'https://share-redirect.invalid' || parsed.search || parsed.hash) return null
    return SHARE_ROUTE_PATTERN.test(parsed.pathname) ? parsed.pathname : null
  } catch {
    return null
  }
}

/** Build the only login location that can preserve a share-flow redirect. */
export function shareLoginLocation(value: unknown): ShareLoginLocation {
  const redirect = sanitizeShareRedirect(value)
  return redirect ? { path: '/login', query: { redirect } } : '/login'
}

/** Resolve the post-login destination without allowing an arbitrary redirect. */
export function resolvePostLoginDestination(
  clientId: 'user' | 'admin',
  value: unknown
): string {
  const redirect = sanitizeShareRedirect(value)
  return redirect && clientId === 'user' ? redirect : clientId === 'admin' ? '/admin' : '/user'
}

/** Build the existing document route from the validated redeem response ID. */
export function shareDocumentRouteFromId(value: unknown): ShareDocumentRouteLocation {
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value <= 0) {
    throw new Error('文档 ID 无效')
  }
  return { name: 'UserDocumentEditor', params: { documentId: String(value) } }
}

/** Extract a validated code from the pathname of the share landing route. */
export function shareLinkCodeFromPath(value: unknown): string | null {
  if (typeof value !== 'string') return null
  const match = SHARE_ROUTE_PATTERN.exec(value)
  return match?.[1] ?? null
}
